name: build
on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: docker://golangci/golangci-lint:v1.43.0
      with:
        args: golangci-lint run
      env:
        CGO_ENABLED: 0
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup kind
      uses: engineerd/setup-kind@v0.5.0
      with:
        version: "v0.11.1"
        image: kindest/node:v1.22.1      
    - name: Setup Vault
      uses: innovationnorway/setup-vault@v1
      with:
        version: '~1.9'
    - name: Setup Go
      uses: actions/setup-go@v1
      with:
        go-version: 1.17
    - name: Show cluster info and configure RBAC
      run: |
        kubectl cluster-info
        echo "current-context:" $(kubectl config current-context)
        echo "environment-kubeconfig:" ${KUBECONFIG}
        kubectl apply -f ci/rbac.yaml
    - name: Run Vault 
      env:
        VAULT_DEV_ROOT_TOKEN_ID: "90b03685-e17b-7e5e-13a0-e14e45baeb2f"
        VAULT_DEV_LISTEN_ADDRESS: "127.0.0.1:8200"
      run: vault server -dev
    - name: Run Unit tests
      run: go test -covermode atomic -coverprofile=profile.cov $(go list -m)/...
    - name: Send coverage
      env:
        COVERALLS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        GO111MODULE=off go get github.com/mattn/goveralls
        $(go env GOPATH)/bin/goveralls -coverprofile=profile.cov -service=github
